/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Meetly API
 * Lightweight Cal.com-подобный сервис записи на встречи.
 *
 * Один глобальный календарь, без авторизации. Владелец публикует типы встреч
 * (разной длительности), гость выбирает тип, день и свободный слот, и бронирует.
 *
 * Все временные метки — в UTC (ISO 8601). Конвертация в локальный часовой пояс
 * выполняется на клиенте.
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

/**
 * Необязательные детали (например, поля, не прошедшие валидацию).
 */
export type ApiErrorDetails = {[key: string]: unknown};

/**
 * Машиночитаемый код ошибки.
 */
export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];


export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  SLOT_TAKEN: 'SLOT_TAKEN',
  SLOT_UNAVAILABLE: 'SLOT_UNAVAILABLE',
  OUT_OF_HORIZON: 'OUT_OF_HORIZON',
  IN_THE_PAST: 'IN_THE_PAST',
  EVENT_TYPE_IN_USE: 'EVENT_TYPE_IN_USE',
} as const;

/**
 * Единый формат тела ошибки для всех эндпоинтов.
 */
export interface ApiError {
  /** Машиночитаемый код ошибки. */
  code: ErrorCode;
  /** Человекочитаемое описание. */
  message: string;
  /** Необязательные детали (например, поля, не прошедшие валидацию). */
  details?: ApiErrorDetails;
}

/**
 * Бронирование встречи.
 */
export interface Booking {
  /** Идентификатор бронирования. */
  id: string;
  /** Идентификатор выбранного типа встречи. */
  eventTypeId: string;
  /** Начало встречи (UTC). */
  slotStart: string;
  /** Конец встречи (UTC). */
  slotEnd: string;
  /** Имя гостя. */
  name: string;
  /** Email гостя. */
  email: string;
  /** Необязательная заметка от гостя. */
  note?: string;
  /** Момент создания брони (UTC). */
  createdAt: string;
}

/**
 * Тело запроса на создание бронирования.
 */
export interface BookingCreate {
  /** Идентификатор выбранного типа встречи. */
  eventTypeId: string;
  /** Начало выбранного слота (UTC). Должно совпадать со свободным слотом. */
  slotStart: string;
  /**
     * Имя гостя.
     * @minLength 1
     * @maxLength 200
     */
  name: string;
  /**
     * Email гостя.
     * @maxLength 320
     */
  email: string;
  /**
     * Необязательная заметка.
     * @maxLength 2000
     */
  note?: string;
}

/**
 * Тип встречи: имя + длительность. Добавление нового типа = одна запись.
 */
export interface EventType {
  /** Идентификатор типа встречи. */
  readonly id: string;
  /**
     * Отображаемое имя, например «Быстрый созвон».
     * @minLength 1
     * @maxLength 120
     */
  name: string;
  /**
     * Человекочитаемый уникальный slug, например `quick-15`.
     * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
     */
  slug: string;
  /**
     * Длительность встречи в минутах (например, 15, 30, 120).
     * @minimum 1
     * @maximum 1440
     */
  durationMinutes: number;
  /**
     * Необязательное описание.
     * @maxLength 1000
     */
  description?: string;
  /** Активен ли тип. Неактивные не показываются гостям. */
  active: boolean;
}

/**
 * Бронирование с развёрнутым типом встречи (для списка владельца).
 */
export interface BookingWithEventType {
  /** Идентификатор бронирования. */
  id: string;
  /** Идентификатор выбранного типа встречи. */
  eventTypeId: string;
  /** Начало встречи (UTC). */
  slotStart: string;
  /** Конец встречи (UTC). */
  slotEnd: string;
  /** Имя гостя. */
  name: string;
  /** Email гостя. */
  email: string;
  /** Необязательная заметка от гостя. */
  note?: string;
  /** Момент создания брони (UTC). */
  createdAt: string;
  /** Развёрнутый тип встречи. */
  eventType: EventType;
}

/**
 * Дата в формате ISO `YYYY-MM-DD`.
 * @pattern ^\d{4}-\d{2}-\d{2}$
 */
export type LocalDate = string;

/**
 * Доступность одного дня — для рендера календаря.
 */
export interface DayAvailability {
  /** День (UTC-дата). */
  date: LocalDate;
  /** Есть ли хотя бы один свободный слот в этот день. */
  available: boolean;
  /** Количество свободных слотов в этот день. */
  slotCount: number;
}

/**
 * Тело запроса на создание типа встречи.
 */
export interface EventTypeCreate {
  /**
     * @minLength 1
     * @maxLength 120
     */
  name: string;
  /** @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$ */
  slug: string;
  /**
     * @minimum 1
     * @maximum 1440
     */
  durationMinutes: number;
  /** @maxLength 1000 */
  description?: string;
  /** По умолчанию `true`. */
  active?: boolean;
}

/**
 * Тело запроса на частичное обновление типа встречи.
 */
export interface EventTypeUpdate {
  /**
     * @minLength 1
     * @maxLength 120
     */
  name?: string;
  /** @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$ */
  slug?: string;
  /**
     * @minimum 1
     * @maximum 1440
     */
  durationMinutes?: number;
  /** @maxLength 1000 */
  description?: string;
  active?: boolean;
}

/**
 * Свободный слот времени.
 */
export interface Slot {
  /** Начало слота (UTC, ISO 8601). */
  start: string;
  /** Конец слота (UTC, ISO 8601), = start + durationMinutes типа встречи. */
  end: string;
}

export type AdminBookingsListParams = {
/**
 * Начало диапазона (включительно), UTC-дата.
 */
from: LocalDate;
/**
 * Конец диапазона (включительно), UTC-дата.
 */
to: LocalDate;
};

export type AvailabilityDaysParams = {
/**
 * Идентификатор типа встречи.
 */
eventTypeId: string;
/**
 * Начало диапазона (включительно), UTC-дата.
 */
from: LocalDate;
/**
 * Конец диапазона (включительно), UTC-дата.
 */
to: LocalDate;
};

export type SlotsListParams = {
/**
 * Идентификатор типа встречи.
 */
eventTypeId: string;
/**
 * День (UTC-дата).
 */
date: LocalDate;
};

export const getMeetlyAPI = (axiosInstance: AxiosInstance = axios.default) => {
/**
 * Список предстоящих встреч в диапазоне, отсортирован по времени начала.
 */
const adminBookingsList = (
    params: AdminBookingsListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BookingWithEventType[]>> => {
    return axiosInstance.get(
      `/api/admin/bookings`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Список всех типов встреч, включая неактивные.
 */
const adminEventTypesList = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<EventType[]>> => {
    return axiosInstance.get(
      `/api/admin/event-types`,options
    );
  }

/**
 * Создать тип встречи.
 */
const adminEventTypesCreate = (
    eventTypeCreate: EventTypeCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<EventType>> => {
    return axiosInstance.post(
      `/api/admin/event-types`,
      eventTypeCreate,options
    );
  }

/**
 * Частично обновить тип встречи (в т.ч. `active=false` — мягкое отключение).
 */
const adminEventTypesUpdate = (
    id: string,
    eventTypeUpdate: EventTypeUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<EventType>> => {
    return axiosInstance.patch(
      `/api/admin/event-types/${id}`,
      eventTypeUpdate,options
    );
  }

/**
 * Удалить тип встречи.
 * Если на тип ссылаются будущие бронирования — возвращает 409 `EVENT_TYPE_IN_USE`;
 * в этом случае следует использовать мягкое отключение (`active=false`).
 */
const adminEventTypesDelete = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/admin/event-types/${id}`,options
    );
  }

/**
 * Доступность по дням в диапазоне `[from, to]` для выбранного типа встречи.
 * Используется для подсветки кликабельных/некликабельных дней в календаре.
 */
const availabilityDays = (
    params: AvailabilityDaysParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DayAvailability[]>> => {
    return axiosInstance.get(
      `/api/availability/days`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Создать бронирование.
 * Сервер перепроверяет доступность слота и атомарно защищается от гонок.
 */
const bookingsCreate = (
    bookingCreate: BookingCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Booking>> => {
    return axiosInstance.post(
      `/api/bookings`,
      bookingCreate,options
    );
  }

/**
 * Получить бронирование по идентификатору (страница подтверждения).
 */
const bookingsGet = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Booking>> => {
    return axiosInstance.get(
      `/api/bookings/${id}`,options
    );
  }

/**
 * Список активных типов встреч.
 */
const eventTypesList = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<EventType[]>> => {
    return axiosInstance.get(
      `/api/event-types`,options
    );
  }

/**
 * Свободные слоты выбранного типа встречи на конкретный день.
 */
const slotsList = (
    params: SlotsListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Slot[]>> => {
    return axiosInstance.get(
      `/api/slots`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

return {adminBookingsList,adminEventTypesList,adminEventTypesCreate,adminEventTypesUpdate,adminEventTypesDelete,availabilityDays,bookingsCreate,bookingsGet,eventTypesList,slotsList}};
export type AdminBookingsListResult = AxiosResponse<BookingWithEventType[]>
export type AdminEventTypesListResult = AxiosResponse<EventType[]>
export type AdminEventTypesCreateResult = AxiosResponse<EventType>
export type AdminEventTypesUpdateResult = AxiosResponse<EventType>
export type AdminEventTypesDeleteResult = AxiosResponse<void>
export type AvailabilityDaysResult = AxiosResponse<DayAvailability[]>
export type BookingsCreateResult = AxiosResponse<Booking>
export type BookingsGetResult = AxiosResponse<Booking>
export type EventTypesListResult = AxiosResponse<EventType[]>
export type SlotsListResult = AxiosResponse<Slot[]>
