name: release-please

on:
  push:
    branches:
      - main  # Запускаться, когда что-то пушится или мержится в ветку main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple  # Используем универсальный тип (создаст version.txt и CHANGELOG.md)